Project updates
stackabletech/zookeeper-operator-integration-tests pull request #10
Opened 2021-08-30 13:31 UTC by lfrancke

2021-09-07 18:26 UTC, soenkeliebau requested changes
Lots of clippy failures in here?

2021-09-07 18:26 UTC, soenkeliebau commented on Cargo.toml
> +integration-test-commons = { git = "https://github.com/stackabletech/integration-test-commons.git", branch = "main" }
Just to double check, the list of needed releases says "no" for integration test commons, is that correct or did we overlook that when deciding what needs releasing?

2021-09-07 18:26 UTC, soenkeliebau commented on Cargo.toml
> +stackable-zookeeper-crd = { git = "https://github.com/stackabletech/zookeeper-operator.git", branch = "main"}
Not sure what the relationship between this and the ZooKeeper operator should be.. is main correct here? This might need to be changed anyway depending on what version of the ZooKeeper operator should be tested..

2021-09-07 18:26 UTC, soenkeliebau commented on deny.toml
> +
I compared this to the Kafka operator "project update" PR and that also had:

> [sources]
> unknown-registry = "deny"
> unknown-git = "deny"

2021-09-08 06:56 UTC, maltesander commented
This one is out of date (Should be merged with [9](https://github.com/stackabletech/zookeeper-operator-integration-tests/pull/9) first. In general i agree. We should tag integration tests for the corresponding operator version? E.g. 0.1.0 zookeeper operator and 0.1.0 integration test?

Then we can always test backwards as well.

2021-09-08 07:25 UTC, maltesander commented on deny.toml
> +
added.

2021-09-08 07:26 UTC, maltesander commented on Cargo.toml
> +integration-test-commons = { git = "https://github.com/stackabletech/integration-test-commons.git", branch = "main" }
We should talk about that. I think every operator release should have a integration test release.

2021-09-13 07:32 UTC, soenkeliebau approved these changes
LGTM

2021-09-13 08:27 UTC, merged