Added files to run integration tests with Stackable CI infrastructure
stackabletech/zookeeper-operator-integration-tests pull request #14
Opened 2021-09-16 16:20 UTC by backstreetkiwi

The integration tests are now run in the new CI (https://ci.stackable.tech). The files in the .ci/ folder contain the cluster definition and test script and execute the same tests as the GitHub Actions workflow test.yml did before. The latter is not deleted but only deactivated, because the transition is not fully completed.

2021-09-16 17:03 UTC, maltesander requested changes
We do not need the node labels anymore. LGTM otherwise.

2021-09-16 17:03 UTC, maltesander commented on .ci/integration-tests/aws-centos-8/test.sh
> +/stackable.sh testdriver-1 -i /.cluster/key 'kubectl label node main-3.stackable.test node=3'
We do not need to label the nodes anymore. The integration will still fail until the scheduling is merged.

2021-09-16 18:39 UTC, backstreetkiwi commented on .ci/integration-tests/aws-centos-8/test.sh
> +/stackable.sh testdriver-1 -i /.cluster/key 'kubectl label node main-3.stackable.test node=3'
Okay, thanks, I will remove the lines.

2021-09-17 08:07 UTC, maltesander approved these changes

2021-09-17 08:14 UTC, merged