Scheduler test
stackabletech/zookeeper-operator-integration-tests pull request #15
Opened 2021-09-20 14:08 UTC by razvan

2021-09-20 15:14 UTC, maltesander requested changes
Just 2 minor things.

2021-09-20 15:14 UTC, maltesander commented on tests/scheduler.rs
> +/// 3. recreates the 3 replicas again and compares the selected node names with the ones from step 1.
In the readme we write of a dynamic amount of nodes (well tested with 3) and @backstreetkiwi uses 3 as well with T2. Can you adapt the docs and notifiy him?

2021-09-20 15:14 UTC, maltesander commented on tests/scheduler.rs
> +    // println!("node_names_2: {:?}", node_names_2);
leftovers?

2021-09-20 15:55 UTC, razvan commented on tests/scheduler.rs
> +/// 3. recreates the 3 replicas again and compares the selected node names with the ones from step 1.
I reduced the required no. of nodes to two and only test with one pod.

2021-09-20 15:56 UTC, razvan commented on tests/scheduler.rs
> +    // println!("node_names_2: {:?}", node_names_2);
Removed,

2021-09-20 18:49 UTC, backstreetkiwi approved these changes
I blackbox-tested this PR in Jenkins: https://ci.stackable.tech/job/Zookeeper%20Operator%20Integration%20Tests/8/

2021-09-21 06:58 UTC, maltesander approved these changes
LGTM.

2021-09-21 06:58 UTC, merged