Use integration-test-commons
stackabletech/zookeeper-operator-integration-tests pull request #4
Opened 2021-06-21 08:40 UTC by maltesander

Currently, the integration tests cover the following cases:

- **Create** a ZooKeeper cluster and check if it is running correctly via the [four letter commands](https://zookeeper.apache.org/doc/r3.4.14/zookeeperAdmin.html#sc_zkCommands) for version 3.5.2 and below or the [admin server commands](https://zookeeper.apache.org/doc/r3.7.0/zookeeperAdmin.html#sc_adminserver) for version 3.5.3 and above.
- **Update** a ZooKeeper cluster from version 3.4.14 to 3.5.8 and check the correctness via the four letter commands or admin server commands.
- **Scale** a ZooKeeper cluster up (e.g., from 1 to 3 nodes) and down (e.g., from 3 to 1 nodes) and check the correctness via four letter commands or admin server commands as well as checking the configmaps which are responsible for transmitting the zoo.cfg config properties.

2021-06-25 15:04 UTC, soenkeliebau approved these changes
I think in principle this is good to go in, I'd be happy to merge this is is and refine over the next months. A lot of this will be extremely fluid for a long time I suspect.
 
I've left a few questions, but most of these are at a fairly high level. 

What it boils down to I think is that we need to come up with a set of requirements and parameters that we want these integration tests to fulfil.

2021-06-25 15:04 UTC, soenkeliebau commented on tests/common/zookeeper.rs
> +/// This returns a ZooKeeper custom resource and the expected pod count (1). We use labels
Wouldn't this fn and the one below it be something that could be substituted for rstest parameterized tests?

2021-07-01 07:18 UTC, maltesander commented on tests/update_cluster.rs
> +    assert_eq!(created_pods.len(), expected_pod_count);
Yeah that is absolutely true. Will remove. Just did not look right to have no asserts at all ;)

2021-07-01 07:19 UTC, maltesander commented on tests/update_cluster.rs
> +    let version = ZookeeperVersion::v3_4_14;
Yes. They do for now, its provided by test-dev-cluster. We will have to tackle that if we want it to run anywhere.

2021-07-08 15:08 UTC, maltesander commented on tests/common/zookeeper.rs
> +/// This returns a ZooKeeper custom resource and the expected pod count (1). We use labels
Yes if we have to cover more cases. This can easily be extracted into rstest if we need so. For the basic tests we have here now i think its enough.

2021-07-08 15:18 UTC, maltesander commented on tests/create_cluster.rs
>      let name = "simple";
I tried it, pod names should not be longer than 63 characters. Which we easily reach if we use that method. I will however create a smaller random uuid to avoid conflicts.

2021-07-08 15:53 UTC, maltesander commented
Should be ready to go, but it works with the zookeeper config branch. Ill wait with merging until that is merged to main.

2021-07-16 07:19 UTC, soenkeliebau requested changes
just one really minor thing

2021-07-29 10:18 UTC, razvan submitted a review, later dismissed
The scaling tests don't work yet. The rest ist ok

2021-07-29 20:24 UTC, soenkeliebau approved these changes
LGTM overall - one question, but happy for it to go in as is as well

2021-07-29 20:24 UTC, soenkeliebau commented on tests/monitoring.rs
> +fn test_monitoring_and_container_ports() -> Result<()> {
Found the reason, I had an old version of the zookeeper-crd crate as a dependency, the struct didn't contain the field `metrics_port` in that version and serde_yaml apparantly simply drops excess fields when deserializing.

2021-08-04 07:25 UTC, soenkeliebau approved these changes
LGTM

2021-08-04 07:29 UTC, merged